DATABASE:
  #POSTGRESQL local environment
  TYPE: POSTGRESQL
  HOST: localhost
  PORT: 5432
  DATABASE: test_pdi_database_n
  USERNAME: postgres
  PASSWORD: 123456

API:
  ENVIRONMENT: DEVELOPMENT
  NAME: Pdi Application(Python Data Integrator)
  IS_DEBUG: False
  PORT: 7100
  SECRET_KEY: s4GGU7jFnKjgu1LsK7fUdxOp1DUSQ-PVgvr28rBNAHM=

APS:
  COALESCE: False
  MAX_INSTANCES: 5
  THREAD_POOL_EXECUTER_COUNT: 10
  PROCESS_POOL_EXECUTER_COUNT: 5